[ruleset]

# Block
Block,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Block.list

# 国内
国内,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs
国内,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs
国内,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.mrs
国内,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list
国内,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs
国内,ipcidr,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs
国内,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
国内,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-cn.mrs

# Test
Test,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list

# Games
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PlayStation/PlayStation.list
Games,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list

# Nvidia
Nvidia,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nvidia/Nvidia.list

# GitHub
GitHub,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs

# AI
AI,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs
AI,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
AI,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Gemini.list
AI,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/groq.mrs
AI,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Grok.list

Meta AI,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list
Copilot AI,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Copilot.list
Perplexity,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/perplexity.mrs

Google,ipcidr,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs
Google,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs

Microsoft,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs

Apple,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs
Apple,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs

Crypto,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/okx.mrs
Crypto,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bybit.mrs
Crypto,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/binance.mrs

Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs
Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs
Stream Media,ipcidr,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs
Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs
Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/amazon.mrs
Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs
Stream Media,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Crunchyroll.list
Stream Media,classical,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Popcorn.list
Stream Media,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs

Social,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/reddit.mrs
Social,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs
Social,classical,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
Social,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/facebook.mrs
Social,domain,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs
Social,ipcidr,https://github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs

国外,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs

[rule]

GEOSITE,geolocation-!cn,国外
MATCH,漏网之鱼
